module.exports = {
  roots: ['<rootDir>/src'],
  collectCoverageFrom: ['src/**/*.{js,jsx,ts,tsx}', '!src/**/*.d.ts', '!__mocks__/**'],
  coveragePathIgnorePatterns: [],
  setupFiles: ['fake-indexeddb/auto'],
  setupFilesAfterEnv: ['./jest/setupTests.ts'],
  testEnvironment: 'jsdom',
  modulePaths: ['<rootDir>/src'],
  transform: {
    '^.+\\.(ts|js|tsx|jsx)$': '@swc/jest',
    '^.+\\.css$': '<rootDir>/jest/cssTransform.js',
    '^(?!.*\\.(js|jsx|mjs|cjs|ts|tsx|css|json)$)': '<rootDir>/jest/fileTransform.js',
  },
  transformIgnorePatterns: [
    '[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
  moduleNameMapper: {
    '@components/(.*)': '<rootDir>/src/components/$1',
    '@configs/(.*)': '<rootDir>/src/configs/$1',
    '@constants/(.*)': '<rootDir>/src/constants/$1',
    '@containers/(.*)': '<rootDir>/src/containers/$1',
    '@hooks/(.*)': '<rootDir>/src/hooks/$1',
    '@store/(.*)': '<rootDir>/src/store/$1',
    '@utils/(.*)': '<rootDir>/src/utils/$1',
    '@testData/(.*)': '<rootDir>/src/testData/$1',
    '@translations/(.*)': '<rootDir>/src/translations/$1',
    '@assets/(.*)': '<rootDir>/src/assets/$1',
    '@pages/(.*)': '<rootDir>/src/pages/$1',
    '@layouts/(.*)': '<rootDir>/src/layouts/$1',
    '@images/(.*)': '<rootDir>/src/images/$1',
    '@mocks/(.*)': '<rootDir>/__mocks__/$1',
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
  },
  moduleFileExtensions: [
    // Place tsx and ts to beginning as suggestion from Jest team
    // https://jestjs.io/docs/configuration#modulefileextensions-arraystring
    'tsx',
    'ts',
    'web.js',
    'js',
    'web.ts',
    'web.tsx',
    'json',
    'web.jsx',
    'jsx',
    'node',
  ],
  watchPlugins: ['jest-watch-typeahead/filename', 'jest-watch-typeahead/testname'],
  resetMocks: true,
};
